# Generated by Django 6.0.1 on 2026-01-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('meal_time', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_response', models.TextField()),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fats_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_analyses', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Meal Analyses',
            },
        ),
        migrations.CreateModel(
            name='WaterIntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_ml', models.IntegerField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('water_time', models.DateTimeField(blank=True, null=True)),
                ('bottle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_date', models.DateField(auto_now_add=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fats_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiber_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sugar_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'diet_date')},
            },
        ),
    ]
