# Generated by Django 6.0.1 on 2026-01-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mealanalysis',
            table='meal_analysis',
        ),
        migrations.AlterModelTable(
            name='requireddietlog',
            table='required_diet_logs',
        ),
    ]
