# Generated by Django 6.0.1 on 2026-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=20)),
                ('dob', models.DateField()),
                ('experience_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Athlete', 'Athlete')], max_length=20, null=True)),
                ('training_goal', models.CharField(choices=[('Fat Loss', 'Fat Loss'), ('Muscle Gain', 'Muscle Gain'), ('Maintain', 'Maintain'), ('Performance', 'Performance')], max_length=20)),
                ('diet_type', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan'), ('Keto', 'Keto'), ('Paleo', 'Paleo')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('food_allergies', models.TextField(blank=True, null=True)),
                ('food_preferences', models.TextField(blank=True, null=True)),
                ('meals_per_day', models.IntegerField(blank=True, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('practice_type', models.JSONField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
